-   name: Update packages.
    apt:
        upgrade: dist
-   name: Install dependencies.
    apt:
        name: "{{ packages }}"
    vars:
        packages:
            - apt-transport-https 
            - ca-certificates 
            - curl 
            - software-properties-common
            - docker.io
            - docker-compose  
