version: "3"
services:
    jenkins:
        image: "jenkins/jenkins:lts"
        container_name: jenkins
        ports:
            - "8080:8080"
            - "5000:5000"
        volumes:
            - jenkins:/var/jenkins_home
            - ./1.Jobs:/opt
volumes:
    jenkins: