version: "3"
services:
    jenkins:
        image: "jenkins-ansible"
        container_name: jenkins
        build: .
        ports:
            - "80:8080"
            - "50000:50000"
        volumes:
            - jenkins:/var/jenkins_home
            - /tmp/:/tmp/
            - ./1.Jobs:/opt
            - ./2.Ansible:/var/jenkins_home/ansible
        networks:
            - net
    
    remote_host:
        container_name: remote-host
        image: remote-host
        build:
            context: centos
        networks:
            - net
volumes:
    jenkins:
networks:
    net: