version: "3"
services:
    jenkins:
        image: "jenkins/jenkins:2.289.1-lts-centos7"
        container_name: jenkins
        ports:
            - "80:8080"
            - "50000:50000"
        volumes:
            - jenkins:/var/jenkins_home
            - /tmp/:/tmp/
            - ./1.Jobs:/opt
volumes:
    jenkins: