version: "3"
services:
    jenkins:
        image: "jenkins/jenkins:2.60.3-alpine"
        container_name: jenkins
        ports:
            - "80:8080"
            - "5000:5000"
        volumes:
            - jenkins:/var/jenkins_home
            - ./1.Jobs:/opt
volumes:
    jenkins: